import Head from "next/head";
import { useState } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UserForm from "@/components/userForm/UserForm";
import AdminList from "@/components/adminList/AdminList";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  //console.log("data:", data);
  const [adminMode, setAdminMode] = useState(false);

  const issues = data.issues.map((issue) => issue.description);
  //console.log("issues", issues, "adminMode", adminMode);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>My city app</h1>{" "}
        <button onClick={() => setAdminMode(!adminMode)}>
          {adminMode === false ? "admin mode" : "user mode"}
        </button>
        {adminMode === false ? <UserForm /> : <AdminList issues={issues} />}
        {/* <UserForm /> */}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(`http://localhost:3000/api/issues`);
  const data = await response.json();
  return { props: { data } };
}
