import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UserForm from "@/components/userForm/UserForm";
// import { PrismaClient } from "@prisma/client";
// export { PrismaClient } from "@prisma/client";

// const prisma = new PrismaClient();
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  console.log("data:", data);

  const issues = data.issues.map((issue) => issue.description);
  console.log("issues", issues);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>My city app</h1>

        <UserForm issues={issues} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(`http://localhost:3000/api/issues`);
  const data = await response.json();
  return { props: { data } };
}
